version: '3'
services:
  BijouBrocProd:
    image: batleforc/bijoubrocprod
    env_file: .env
    restart: always
    environment:
      - SERVER=bijoubroc.weebo.fr
    container_name: ProdBijouBrocApi
    volumes:
      - ./:/srv/app
      - /home/max/Docker/bijoubroc/data/prod:/srv/app/public/uploads
    expose:
      - 1337
    networks:
      - bijoubroc
      - weebo
networks:
  bijoubroc:
    name: bijoubroc
  weebo:
    name: weebo