version: '3'
services:
  BijouBrocDev:
    image: strapi/strapi:latest
    env_file: .env
    container_name: DevBijouBrocApi
    volumes:
      - ./:/srv/app
    ports:
      - '1337:1337'
    networks:
      - bijoubroc
      - weebo
networks:
  bijoubroc:
    name: bijoubroc
  weebo:
    name: weebo