version: '3'
services:
  BijouBrocProd:
    image: batleforc/bijoubroc
    env_file: .env
    container_name: ProdBijouBrocApi
    volumes:
      - ./:/srv/app
    expose:
      - 1337
    networks:
      - bijoubroc
      - weebo
networks:
  bijoubroc:
    name: bijoubroc
  weebo:
    name: weebo