version: '3'
services:
  BijouBrocDev:
    image: batleforc/bijoubrocprod
    env_file: .env
    restart: always
    container_name: DevBijouBrocApi
    volumes:
      - ./:/srv/app
      - /home/max/Docker/bijoubroc/data/dev:/srv/app/public/uploads
    expose:
      - 1337
    networks:
      - bijoubroc
      - weebo
networks:
  bijoubroc:
    name: bijoubroc
  weebo:
    name: weebo