version: '3'
services:
  strapi:
    image: strapi/strapi
    env_file: .env
    container_name: BijouBrocApi
    volumes:
      - ./:/srv/app
    ports:
      - '1337:1337'
    networks:
      - bijoubroc
      - weebo
networks:
  bijoubroc:
    name: bijoubroc
  weebo:
    name: weebo