name: BijouBrocApi:Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: echo "$dotenv" > ./.env
        shell: bash
        env:
          dotenv: ${{secrets.DOTENV}}
      - run: docker build -t batleforc/bijoubroc .
      - run: docker-compose -f docker-composeProd.yml up -d
