name: BijouBrocApi:Dev:Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, dev]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: echo "$dotenv" > ./.env
        shell: bash
        env:
          dotenv: ${{secrets.DOTENVDEV}}
      - run: docker-compose -f docker-composeDev.yml up -d
