name: BijouBrocApi:Prod:Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, prod]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: echo "$dotenv" > ./.env
        shell: bash
        env:
          dotenv: ${{secrets.DOTENVPROD}}
      - run: echo "SERVER=bijoubroc.weebo.fr" >> ./.env
        shell: bash
      - run: docker build -t batleforc/bijoubrocprod .
      - run: docker-compose -f docker-composeProd.yml up -d
